# Question 1
1)  A function that takes a NumPy array of integer numbers and returns a NumPy array of
the cube of each the array elements. Your function must use the NumPy universal
function power(). Note you must NOT use for loops to access NumPy array elements​

In [1]:
import numpy as np

def numpyCube(nparray):
    return np.power(nparray,3) #return the cube of the nparray using power() function

#check the result
numpy_cube_result = numpyCube(np.arange(10))
print (numpy_cube_result)
    

[  0   1   8  27  64 125 216 343 512 729]


2) A function that takes a Python sequence (range) of integer numbers and returns a python list of the cube of each of the range elements using the Python pow() function.

In [2]:
def rangeCube(rangearray):
    result = [] #create a empty list
    for x in rangearray: #loop through the element
        result.append(pow(x,3)) #append the cube of each elemen into the result list
    return result

#check the result
range_cube_result = rangeCube(range(10))
print(range_cube_result)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


# Q1 Create two variables:
1) narray a NumPy array of 100,000 integer numbers

2) nlist a Python list of 100,000 integer numbers

In [70]:
# 1) narray a NumPy array of 100,000 integer numbers
narray = np.arange(100000) 
print('array by NumPy:')
print(numpyCube(narray))

# 2) nlist a Python list of 100,000 integer numbers
nlist = range(100000)
print('array by Python list:')
print(rangeCube(nlist))

array by NumPy:
[              0               1               8 ... 999910002699973
 999940001199992 999970000299999]
array by Python list:
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000, 9261, 10648, 12167, 13824, 15625, 17576, 19683, 21952, 24389, 27000, 29791, 32768, 35937, 39304, 42875, 46656, 50653, 54872, 59319, 64000, 68921, 74088, 79507, 85184, 91125, 97336, 103823, 110592, 117649, 125000, 132651, 140608, 148877, 157464, 166375, 175616, 185193, 195112, 205379, 216000, 226981, 238328, 250047, 262144, 274625, 287496, 300763, 314432, 328509, 343000, 357911, 373248, 389017, 405224, 421875, 438976, 456533, 474552, 493039, 512000, 531441, 551368, 571787, 592704, 614125, 636056, 658503, 681472, 704969, 729000, 753571, 778688, 804357, 830584, 857375, 884736, 912673, 941192, 970299, 1000000, 1030301, 1061208, 1092727, 1124864, 1157625, 1191016, 1225043, 1259712, 1295029, 1331000, 1367631, 1404928, 1442897, 1481544, 1520875, 1

# Q2 
Use %timeit to determine how much faster your function using NumPy arrays is versus your
function that uses a sequence. Include your conclusions in your Jupyter Notebook in a mark-
down cell with an explanation of why Q1 did not allow loops to be used in the function.

Function using sequence takes 28ms which equals to 28000us
Function using Numpy arrays takes 124 us and 28000/124 = 225, 
which is 225 times faster than Function using sequence.

Looping through the sequence is very time consuming. 
That is the reason why loops is restricted for function using NumPy and using Numpy universal function power() is much faster without looping through every element in the array.

In [4]:
%timeit numpy_time = numpyCube(narray)
%timeit list_time = rangeCube(nlist)

129 µs ± 2.55 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
28.1 ms ± 356 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Q3.
This question requires you to manipulate arrays using slicing, splitting and/or array func-
tions (e.g. append, row_stack, column_stack):

a) Generate a 1D array of the values from 1 to 20. Use a single line of code to convert
the array to a 2D array of 4 rows by 5 columns.

b) Look up the NumPy array functions and find the function that will revert your array
back to a 1D array. Apply this to your array.

c) Create the following two NumPy arrays: A and B, 
and Create a third NumPy array where the values are the multiplication of the values of array
A and B for each row, column position. In positions where one of the arrays does not have
a value to use, copy the single value from the other array.

In [71]:
# a) Generate a 1D array of the values from 1 to 20. 
Darray = np.arange(20)
print('1D array of the values from 1 to 20:')
print(Darray)

#Use a single line of code to convert the array to a 2D array of 4 rows by 5 columns.
Darray = Darray.reshape(4,5)
print('2D array of 4 rows by 5 columns:')
print(Darray)

1D array of the values from 1 to 20:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2D array of 4 rows by 5 columns:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [72]:
#b) Look up the NumPy array functions and find the function that will revert your array back to a 1D array. 
Darray = Darray.ravel()
print('array back to a 1D array:')
print(Darray)

array back to a 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [69]:
#c) Create the following two NumPy arrays: A and B
a,b = np.split(np.arange(10) + 1,[4]) #create an [1,2,...,10] sequence and split into [1,2,3,4] and [5,6,...,10]

array_A = a.reshape(2,2) #reshape into 2d array
array_B = b.reshape(2,3) #reshape into 2d array

print("Array:A")
print(array_A)
print("Array:B")
print(array_B)

#print(array_A.ndim)
#print(array_B.ndim)

def arrayC(arrayA,arrayB):
    
    ##test code##print(f'This is arrayA shape:{arrayA.shape}')
    ##test code##print(f'This is arrayA :\n{arrayA}')
    
    ##test code##print(f'This is arrayB shape:{arrayB.shape}')
    ##test code##print(f'This is arrayB :\n{arrayB}')
    
    #check max dimension of array A and B
    dimension_arrayC = np.max([arrayA.ndim,arrayB.ndim])
    
    while arrayA.ndim < dimension_arrayC:
        arrayA = arrayA[...,np.newaxis]
        
    while arrayB.ndim < dimension_arrayC:
        arrayB = arrayB[...,np.newaxis]
    
    shape_arrayC = []
    #set height of arrayC to the max(height of arrayA,height of arrayB)
    for i in range(dimension_arrayC):
        try:
            shape_arrayC.append(max(arrayA.shape[i],arrayB.shape[i]))
        except:
            try:
                shape_arrayC.append(arrayA.shape[i])
            except:
                shape_arrayC.append(arrayB.shape[i])
        
    ##test code##print(f'This is shape of C:{shape_arrayC}')
    
    #create arrayC and filled with all ones
    arrayC = np.ones((shape_arrayC),dtype=int)
    #create new_arrayA and new_arrayB with dimension of arrayC and filled with all ones
    new_arrayA = np.ones((shape_arrayC),dtype=int)
    new_arrayB = np.ones((shape_arrayC),dtype=int)
    #copy the original arrayA and arrayB into new array with a 
    new_arrayA[tuple(map(slice, arrayA.shape))] = arrayA
    ##test code##print(f'This is new arrayA:\n{new_arrayA}')
    
    new_arrayB[tuple(map(slice, arrayB.shape))] = arrayB
    
    ##test code##print(f'This is new arrayB:\n{new_arrayB}')
    
    arrayC = new_arrayA * new_arrayB
    ##test code##print(f'This is arrayC:\n{arrayC}')
    
    return arrayC

print(f'This is arrayC:\n{arrayC(array_A,array_B)}')

print("\nTest case for function")
testA = np.asarray([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
testB = np.asarray([[1,3],[2,3],[3,3],[4,3]])

print("test:A")
print(testA)
print("test:B")
print(testB)

print(f'This is test case:\n{arrayC(testA,testB)}')


#print("\nTest 2 case for function")
#testA = np.asarray([[[[1, 2, 3, 4], [3, 4, 5,6]], [[5, 6, 7,8], [7, 8, 9, 10]]],[[[1, 2, 3, 4], [3, 4, 5,6]], [[5, 6, 7,8], [7, 8, 9, 10]]]])
#testB = np.asarray([[1,3],[2,3],[3,3],[4,3]])

#arrayC(testA,testB)

Array:A
[[1 2]
 [3 4]]
Array:B
[[ 5  6  7]
 [ 8  9 10]]
This is arrayC:
[[ 5 12  7]
 [24 36 10]]

Test case for function
test:A
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
test:B
[[1 3]
 [2 3]
 [3 3]
 [4 3]]
This is test case:
[[[ 1  2  3]
  [ 9  4  5]]

 [[10  6  7]
  [21  8  9]]

 [[ 3  1  1]
  [ 3  1  1]]

 [[ 4  1  1]
  [ 3  1  1]]]


In [84]:
#test code for arrayB
testA = np.asarray([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
testB = np.asarray([[1,3],[2,3],[3,3],[4,3]])

print("test:A")
print(testA)
print(testA.shape)
print("test:B")
print(testB)
print(testB.shape)

print(f'This is test C:\n{arrayC(testA,testB)}')
print(arrayC(testA,testB).shape)


test:A
[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
(2, 2, 3)
test:B
[[1 3]
 [2 3]
 [3 3]
 [4 3]]
(4, 2)
This is test C:
[[[ 1  2  3]
  [ 9  4  5]]

 [[10  6  7]
  [21  8  9]]

 [[ 3  1  1]
  [ 3  1  1]]

 [[ 4  1  1]
  [ 3  1  1]]]
(4, 2, 3)


In [85]:
kH = [[[1 ,3 ,1],
 [2, 3 ,1]],
 [[3, 3, 1],
 [4, 3, 1]],
[[1, 1, 1],
 [1, 1, 1]],
[[1, 1, 1],
   [1, 1, 1]]]

kH = np.asarray(kH)

kH.shape

(4, 2, 3)

In [92]:
D = np.array([[[1,3,1],
              [2,3,1],
[3,3,1],
[4,3,1]],
[[1,1,1],
[1,1,1],
[1,1,1]]])

In [93]:
D.shape

(2,)

In [94]:
D = np.array([[[1,3,1],
              [2,3,1],
[3,3,1],
[4,3,1]],
[[1,1,1],
[1,1,1],
[1,1,1],
[1,1,1]]])

In [95]:
D.shape

(2, 4, 3)